version: '3.8'

services:
  admin:
    build: .
    command: ["python", "admin.py"]
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  user:
    build: .
    command: ["python", "user.py"]
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data