version: '3.8'

services:
  admin:
    build: .
    command: ["python", "admin.py"]
    restart: always
    env_file:
      - .env

  user:
    build: .
    command: ["python", "user.py"]
    restart: always
    env_file:
      - .env